### ISSUE TITLE
Unable to create poltype2 conda environment due to conflicts between packages

### ISSUE THREAD

**Issue by JMorado** [TinkerTools/poltype2#45]
Hello,

I'm encountering difficulties installing the conda environment required for running poltype2. I've tried both the `conda env create -f environment.yml` method and the approach outlined [here](https://github.com/TinkerTools/poltype2/blob/master/README/README_INSTALL.MD#explicit-conda-installation), but both have resulted in conflicts between packages.

Do you have any suggestions on how to overcome this? Is it possible to provide a more general `env.yml` file that doesn't explicitly list every package (including dependencies of main packages)? Ideally, this `env.yml` file should not explicitly specify the packages builds, as this often ties them to specific architectures and operating systems, making them less portable in many instances.

Thank you in advance for your assistance.

**Comment by JMorado** [comment]
In case it is useful to someone, I have managed to create the conda environment required to run poltype by using the following yaml file:

```yaml
name: poltype2
channels:
  - conda-forge
  - rdkit
  - salilab
dependencies:
  - micromamba
  - psi4
  - geometric
  - mdanalysis
  - openbabel
  - svgutils
  - cairosvg
  - psutil
  - mdtraj
  - openpyxl
  - pdb2pqr
  - pdbfixer
  - rdkit
  - modeller
  - gdma
  - pip
  - pip:
    - pymbar
    - PyAstronomy
```
